services:
  notification:
    image: ghcr.io/yueli-official/notification:latest
    container_name: notification
    platform: linux/amd64
    ports:
      - "9000:9000"
    volumes:
      - ./config.toml:/app/config.toml:ro
    environment:
      - TZ=Asia/Shanghai
